# -*- coding: utf-8 -*-
"""M3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IdNCsxZBP41NHmMSJfkIvzsGnnLGdxoC

# Import library
"""

import cv2
import numpy as np
import urllib.request
import matplotlib.pyplot as plt

"""# download & load image"""

url = 'https://raw.githubusercontent.com/opencv/opencv/master/samples/data/lena.jpg'
urllib.request.urlretrieve(url, 'lena.jpg')
print("✅ lena.jpg berhasil diunduh!")

img = cv2.imread("lena.jpg", 0)
plt.imshow(img,cmap='gray')
plt.axis('off')
plt.show()

"""# brightening"""

bright_value = 50
bright = cv2.add(img,bright_value* np.ones(img.shape, dtype= np.uint8))

plt.figure(figsize = (8,4))
plt.subplot(1,2,1), plt.imshow(img,cmap= 'gray'), plt.title("Original"), plt.axis('off')
plt.subplot(1,2,2), plt.imshow(bright,cmap= 'gray'), plt.title("Brightened"), plt.axis('off')
plt.show()

"""# THRESHOLDING"""

if img is None:
    print("Gambar tidak ditemukan!")
else:
    _, thresh_binary = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)
    _, thresh_binary_inv= cv2.threshold(img, 127, 255, cv2.THRESH_BINARY_INV)

plt.figure(figsize = (8,4))
plt.subplot(1,3,1), plt.imshow(img,cmap= 'gray'), plt.title("Original"), plt.axis('off')
plt.subplot(1,3,2), plt.imshow(thresh_binary,cmap= 'gray'), plt.title("Binary"), plt.axis('off')
plt.subplot(1,3,3), plt.imshow(thresh_binary_inv,cmap= 'gray'), plt.title("Binary Inv"), plt.axis('off')

plt.show()

"""# negatif digital"""

if img is None:
    print("Gambar tidak ditemukan!")
else:
    negatif = 255-img

plt.figure(figsize = (8,4))
plt.subplot(1,2,1), plt.imshow(img,cmap= 'gray'), plt.title("Original"), plt.axis('off')
plt.subplot(1,2,2), plt.imshow(negatif,cmap= 'gray'), plt.title("Negatif Digital"), plt.axis('off')
plt.show()

"""# Clipping"""

if img is None:
    print("Gambar tidak ditemukan!")
else:
    min_val, max_val = 100,200
    clipping = np.clip(img, min_val, max_val)
plt.figure(figsize = (8,4))
plt.subplot(1,2,1), plt.imshow(img,cmap= 'gray'), plt.title("Original"), plt.axis('off')
plt.subplot(1,2,2), plt.imshow(clipping,cmap= 'gray'), plt.title(f"Clipping[{min_val}-{max_val}]"), plt.axis('off')
plt.tight_layout()
plt.show()

