# -*- coding: utf-8 -*-
"""m2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-WP2Caa4PYuvHo3GSXeBLGWtsvV14j-o

# import library
"""

import cv2
import urllib.request
import numpy as np
import matplotlib.pyplot as plt

"""# Download & load image"""

url = 'https://raw.githubusercontent.com/opencv/opencv/master/samples/data/lena.jpg'
urllib.request.urlretrieve(url, 'lena.jpg')
print("✅ lena.jpg berhasil diunduh!")

img = cv2.imread("lena.jpg")
rows, cols = img.shape[:2]

def show_and_save(win, image, filename = None):
    cv2.imshow(win, image)
    if filename:
        cv2.imwrite(filename, image)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

"""# Translasi"""

tx, ty = 50, 100
M = np.float32([[1, 0 , tx],[0, 1, ty]])
dst = cv2.warpAffine(img, M, (cols, rows))
show_and_save("Translasi", dst, "translasi.jpg")

"""# ROTASI"""

center = (cols/2, rows/2)
angle = 45
M = cv2.getRotationMatrix2D(center, angle, 1.0)
dst = cv2.warpAffine(img,M,(cols,rows))
show_and_save("Rotasi",dst,"rotasi.jpg")

"""# Scaling"""

dst = cv2.resize(img, None, fx = 0.5, fy=0.5, interpolation=cv2.INTER_AREA)
show_and_save("Scaling",dst,"rotasi.jpg")

"""# Menampilkan di cell"""

image = cv2.imread("lena.jpg")
rows, cols = image.shape[:2]

#translasi
tx, ty = 50, 100
M_translasi = np.float32([[1, 0 , tx],[0, 1, ty]])
dst_translasi = cv2.warpAffine(img, M_translasi, (cols, rows))

#rotasi
center = (cols/2, rows/2)
angle = 45
M_rotasi = cv2.getRotationMatrix2D(center, angle, 1.0)
dst_rotasi = cv2.warpAffine(img,M_rotasi,(cols,rows))

#Scaling
img_scaling = cv2.resize(img, None, fx = 0.5, fy=0.5, interpolation=cv2.INTER_AREA)

image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
img_translasi_rgb = cv2.cvtColor(dst_translasi, cv2.COLOR_BGR2RGB)
img_rotasi_rgb = cv2.cvtColor(dst_rotasi, cv2.COLOR_BGR2RGB)
img_scaling_rgb = cv2.cvtColor(img_scaling, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(12, 8))

plt.subplot(2, 2, 1)
plt.imshow(image_rgb)
plt.title("Gambar Asli")
plt.axis("off")

plt.subplot(2, 2, 2)
plt.imshow(img_translasi_rgb)
plt.title("Translasi (Geser)")
plt.axis("off")

plt.subplot(2, 2, 3)
plt.imshow(img_rotasi_rgb)
plt.title("Rotasi (45°)")
plt.axis("off")

plt.subplot(2, 2, 4)
plt.imshow(img_scaling_rgb)
plt.title("Scaling (0.1x)")
plt.axis("off")

plt.tight_layout()
plt.show()

