# -*- coding: utf-8 -*-
"""M6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17mMv6T6Gg1by7Lr_CUJ8AnNWU7JourPy

# Import Libraries & Load Iamge
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import urllib.request

"""# Download & Load Image"""

url = 'https://www.tagar.id/Asset/uploads/2017/09/Macan-Tutul-Jawa-Panthera-Pardus-Melas.jpg'
urllib.request.urlretrieve(url, 'macan.jpeg')

img = cv2.imread("macan.jpeg")

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("Macan Tutul")
plt.axis("off")
plt.show()

plt.figure(figsize=(6,5))
plt.imshow(img,cmap='gray')
plt.axis('off')
plt.show()

"""# Sobel"""

s_x = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
s_y = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)
s_mag = cv2.magnitude(s_x, s_y)

sobel_x = cv2.convertScaleAbs(s_x)
sobel_y = cv2.convertScaleAbs(s_y)
sobel_magnitude = cv2.convertScaleAbs(s_mag)

plt.figure(figsize=(15,4))

plt.subplot(1,3,1)
plt.imshow(sobel_x, cmap='gray')
plt.title('Sobel X')
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(sobel_y, cmap='gray')
plt.title('Sobel Y')
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(sobel_magnitude, cmap='gray')
plt.title('Sobel Magnitude')
plt.axis('off')

plt.show()

"""# Canny"""

canny = cv2.Canny(img, 75, 200)

plt.figure(figsize=(6,5))
plt.imshow(canny, cmap='gray')
plt.title('Canny')
plt.axis('off')

plt.show()

"""# Orde Kedua"""

blur = cv2.GaussianBlur(img, (5,5), sigmaX=0)
lap = cv2.Laplacian(blur,cv2.CV_64F)
log = cv2.convertScaleAbs(lap)

plt.figure(figsize=(6,5))
plt.imshow(log, cmap='gray')
plt.title('Log (Laplacian + Gaussian)')
plt.axis('off')

plt.show()

