# -*- coding: utf-8 -*-
"""m5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RzdX5yHrK4Qz1Y5ipxzpsQwjME_Bhq4v

# Import Library
"""

import cv2
import numpy as np
import urllib.request
import matplotlib.pyplot as plt

"""# download image"""

url = 'https://user-images.githubusercontent.com/85081014/224490404-568cdeaa-8013-449a-b79d-ea9c320fd677.png'
urllib.request.urlretrieve(url, 'lena.jpg')
print("✅ lena.jpg berhasil diunduh!")

"""# markdown"""

img = cv2.imread('lena.jpg', cv2.IMREAD_GRAYSCALE)

"""# Filtering spasial"""

kernel_smooth = np.ones((5,5), np.float32)/25
smooth = cv2.filter2D(img, -1, kernel_smooth)

plt.figure(figsize=(8,4))
plt.subplot(1,2,1), plt.imshow(img, cmap='gray'), plt.title('Original')
plt.axis('off')
plt.subplot(1,2,2), plt.imshow(smooth, cmap='gray'), plt.title('Smoothing(LSP)')
plt.axis('off')
plt.show()

median =  cv2.medianBlur(img, 5)
plt.figure(figsize=(8,4))
plt.subplot(1,2,1), plt.imshow(img, cmap='gray'), plt.title('Original')
plt.axis('off')
plt.subplot(1,2,2), plt.imshow(median, cmap='gray'), plt.title('Median')
plt.axis('off')
plt.show()

kernel_sharp = np.array([[0,-1,0],
                       [-1,5,-1],
                       [0,-1,0]])
sharp = cv2.filter2D(median, -1, kernel_sharp)
plt.figure(figsize=(8,4))
plt.subplot(1,2,1), plt.imshow(median, cmap='gray'), plt.title('Median')
plt.axis('off')
plt.subplot(1,2,2), plt.imshow(sharp, cmap='gray'), plt.title('Sharpening')
plt.axis('off')
plt.show()

edge = cv2.Sobel(sharp, cv2.CV_64F, 1, 1, ksize = 3)
edge = cv2.convertScaleAbs(edge)

plt.figure(figsize=(8,4))
plt.subplot(1,2,1), plt.imshow(sharp, cmap='gray'), plt.title('Sharp')
plt.axis('off')
plt.subplot(1,2,2), plt.imshow(edge, cmap='gray'), plt.title('Edge')
plt.axis('off')
plt.show()

gaussian = cv2.GaussianBlur (img, (5,5), 0)

plt.figure(figsize=(8,4))
plt.subplot(1,2,1), plt.imshow(img, cmap='gray'), plt.title('Original')
plt.axis('off')
plt.subplot(1,2,2), plt.imshow(gaussian, cmap='gray'), plt.title('Gaussian')
plt.axis('off')
plt.show()

